import jsPDF from 'jspdf';
import type { Invoice } from '@/types/invoice';

export function generateInvoicePDF(invoice: Invoice): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let y = 20;

  // Company Header
  doc.setFontSize(24);
  doc.setTextColor(232, 52, 78); // Red color
  doc.text('GuriGate', 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('Property Management System', 20, y);
  y += 5;
  doc.text('Somalia', 20, y);
  y += 20;

  // Invoice Title
  doc.setFontSize(18);
  doc.setTextColor(0);
  doc.text('INVOICE', pageWidth - 20, y, { align: 'right' });
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Invoice Number: ${invoice.invoiceNumber}`, pageWidth - 20, y, { align: 'right' });
  y += 6;
  doc.text(`Issue Date: ${new Date(invoice.issueDate).toLocaleDateString()}`, pageWidth - 20, y, { align: 'right' });
  y += 6;
  doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, pageWidth - 20, y, { align: 'right' });
  y += 20;

  // Customer Information
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('Bill To:', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Customer: ${invoice.tenantName || 'N/A'}`, 20, y);
  y += 6;
  doc.text(`Property: ${invoice.propertyName || 'N/A'}`, 20, y);
  y += 6;
  doc.text(`Unit: ${invoice.unitId || 'N/A'}`, 20, y);
  y += 20;

  // Line separator
  doc.setDrawColor(200);
  doc.line(20, y, pageWidth - 20, y);
  y += 15;

  // Invoice Details Table
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('Invoice Details', 20, y);
  y += 10;

  const tableData = [
    ['Description', 'Amount'],
    ['Rent / Subtotal', formatCurrency(invoice.subtotal)],
  ];

  if (invoice.additionalCharges > 0) {
    tableData.push(['Additional Charges', formatCurrency(invoice.additionalCharges)]);
  }

  if (invoice.discount > 0) {
    tableData.push(['Discount', `-${formatCurrency(invoice.discount)}`]);
  }

  if (invoice.tax > 0) {
    tableData.push(['Tax', formatCurrency(invoice.tax)]);
  }

  tableData.push(['Total', formatCurrency(invoice.totalAmount)]);

  // Draw table
  const colWidths = [pageWidth - 100, 60];
  const rowHeight = 10;

  tableData.forEach((row, i) => {
    if (i === 0) {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
    } else {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
    }

    doc.text(row[0], 20, y);
    doc.text(row[1], pageWidth - 60, y, { align: 'right' });
    y += rowHeight;
  });

  y += 15;

  // Payment Information
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text('Payment Information', 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Paid Amount: ${formatCurrency(invoice.paidAmount)}`, 20, y);
  y += 6;
  doc.text(`Balance Due: ${formatCurrency(invoice.balanceDue)}`, 20, y);
  y += 6;
  doc.text(`Status: ${invoice.status.toUpperCase()}`, 20, y);
  y += 20;

  // Notes
  if (invoice.notes) {
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text('Notes', 20, y);
    y += 10;

    doc.setFontSize(10);
    doc.setTextColor(100);
    const splitNotes = doc.splitTextToSize(invoice.notes, pageWidth - 40);
    doc.text(splitNotes, 20, y);
    y += splitNotes.length * 6 + 15;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by GuriGate Property Management System', 20, pageHeight - 20);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth - 20, pageHeight - 20, { align: 'right' });

  // Save PDF
  doc.save(`Invoice_${invoice.invoiceNumber}.pdf`);
}

function formatCurrency(amount: number): string {
  return `$${amount.toFixed(2)}`;
}
